//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class libro
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public int genero { get; set; }
        public int año { get; set; }
        public int edicion { get; set; }
        public string portada { get; set; }
        public Nullable<int> autor { get; set; }
    }
}
